/* DO NOT EDIT!  -*- buffer-read-only: t -*-  This file is automatically
 * generated from MDS
 */

#ifndef __KV3_MPPADL_RELOC_MDS_H__
#define __KV3_MPPADL_RELOC_MDS_H__


enum MPPA_DL_RELOCATIONS {
     R_KVX_NONE                                  = 0,
     R_KVX_16                                    = 1,
     R_KVX_32                                    = 2,
     R_KVX_64                                    = 3,
     R_KVX_S16_PCREL                             = 4,
     R_KVX_PCREL17                               = 5,
     R_KVX_PCREL27                               = 6,
     R_KVX_32_PCREL                              = 7,
     R_KVX_S37_PCREL_LO10                        = 8,
     R_KVX_S37_PCREL_UP27                        = 9,
     R_KVX_S43_PCREL_LO10                        =10,
     R_KVX_S43_PCREL_UP27                        =11,
     R_KVX_S43_PCREL_EX6                         =12,
     R_KVX_S64_PCREL_LO10                        =13,
     R_KVX_S64_PCREL_UP27                        =14,
     R_KVX_S64_PCREL_EX27                        =15,
     R_KVX_64_PCREL                              =16,
     R_KVX_S16                                   =17,
     R_KVX_S32_LO5                               =18,
     R_KVX_S32_UP27                              =19,
     R_KVX_S37_LO10                              =20,
     R_KVX_S37_UP27                              =21,
     R_KVX_S37_GOTOFF_LO10                       =22,
     R_KVX_S37_GOTOFF_UP27                       =23,
     R_KVX_S43_GOTOFF_LO10                       =24,
     R_KVX_S43_GOTOFF_UP27                       =25,
     R_KVX_S43_GOTOFF_EX6                        =26,
     R_KVX_32_GOTOFF                             =27,
     R_KVX_64_GOTOFF                             =28,
     R_KVX_32_GOT                                =29,
     R_KVX_S37_GOT_LO10                          =30,
     R_KVX_S37_GOT_UP27                          =31,
     R_KVX_S43_GOT_LO10                          =32,
     R_KVX_S43_GOT_UP27                          =33,
     R_KVX_S43_GOT_EX6                           =34,
     R_KVX_64_GOT                                =35,
     R_KVX_GLOB_DAT                              =36,
     R_KVX_COPY                                  =37,
     R_KVX_JMP_SLOT                              =38,
     R_KVX_RELATIVE                              =39,
     R_KVX_S43_LO10                              =40,
     R_KVX_S43_UP27                              =41,
     R_KVX_S43_EX6                               =42,
     R_KVX_S64_LO10                              =43,
     R_KVX_S64_UP27                              =44,
     R_KVX_S64_EX27                              =45,
     R_KVX_S37_GOTADDR_LO10                      =46,
     R_KVX_S37_GOTADDR_UP27                      =47,
     R_KVX_S43_GOTADDR_LO10                      =48,
     R_KVX_S43_GOTADDR_UP27                      =49,
     R_KVX_S43_GOTADDR_EX6                       =50,
     R_KVX_S64_GOTADDR_LO10                      =51,
     R_KVX_S64_GOTADDR_UP27                      =52,
     R_KVX_S64_GOTADDR_EX27                      =53,
     R_KVX_64_DTPMOD                             =54,
     R_KVX_64_DTPOFF                             =55,
     R_KVX_S37_TLS_DTPOFF_LO10                   =56,
     R_KVX_S37_TLS_DTPOFF_UP27                   =57,
     R_KVX_S43_TLS_DTPOFF_LO10                   =58,
     R_KVX_S43_TLS_DTPOFF_UP27                   =59,
     R_KVX_S43_TLS_DTPOFF_EX6                    =60,
     R_KVX_S37_TLS_GD_LO10                       =61,
     R_KVX_S37_TLS_GD_UP27                       =62,
     R_KVX_S43_TLS_GD_LO10                       =63,
     R_KVX_S43_TLS_GD_UP27                       =64,
     R_KVX_S43_TLS_GD_EX6                        =65,
     R_KVX_S37_TLS_LD_LO10                       =66,
     R_KVX_S37_TLS_LD_UP27                       =67,
     R_KVX_S43_TLS_LD_LO10                       =68,
     R_KVX_S43_TLS_LD_UP27                       =69,
     R_KVX_S43_TLS_LD_EX6                        =70,
     R_KVX_64_TPOFF                              =71,
     R_KVX_S37_TLS_IE_LO10                       =72,
     R_KVX_S37_TLS_IE_UP27                       =73,
     R_KVX_S43_TLS_IE_LO10                       =74,
     R_KVX_S43_TLS_IE_UP27                       =75,
     R_KVX_S43_TLS_IE_EX6                        =76,
     R_KVX_S37_TLS_LE_LO10                       =77,
     R_KVX_S37_TLS_LE_UP27                       =78,
     R_KVX_S43_TLS_LE_LO10                       =79,
     R_KVX_S43_TLS_LE_UP27                       =80,
     R_KVX_S43_TLS_LE_EX6                        =81,
};
#endif /* __KV3_MPPADL_RELOC_MDS_H__ */
